### ISSUE TITLE
Can't import node:  No module named 'google.cloud'

### ISSUE THREAD

**Issue by jelling** [Fantaxico/ComfyUI-GCP-Storage#3]
It looks like the node is missing either instructions or code to install the necessary GCP module:

```
Traceback (most recent call last):
  File "/workspace/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-GCP-Storage/__init__.py", line 14, in <module>
    from .gcp_storage import NODE_CLASS_MAPPINGS
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-GCP-Storage/gcp_storage.py", line 1, in <module>
    from google.cloud import storage
ModuleNotFoundError: No module named 'google.cloud'

Cannot import /workspace/ComfyUI/custom_nodes/ComfyUI-GCP-Storage module for custom nodes: No module named 'google.cloud'
```

I tried installing `google-cloud` and `google-cloud-storage` into both the `venv` for Comfy and the global space. Neither worked.

**Comment by aurel-g** [comment]
For me, installing `google-cloud-storage` package (in the venv) did the trick.
